// Generated by CoffeeScript 1.3.3
(function() {
  var Beam, Fighter, Invader,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  enchant();

  Invader = (function(_super) {

    __extends(Invader, _super);

    Invader.prototype.config = {
      WIDTH: 360,
      HEIGHT: 480,
      FPS: 30,
      IMAGES: ["image/apple.png", "image/laser.png", "image/beam.png", "image/droid.png"]
    };

    function Invader() {
      var count, enemy, i, score, scoreLabel, total, _i, _len, _ref,
        _this = this;
      Invader.__super__.constructor.call(this, this.config.WIDTH, this.config.HEIGHT);
      this.fps = this.config.FPS;
      _ref = this.config.IMAGES;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        this.preload(i);
      }
      this.rootScene.backgroundColor = "black";
      scoreLabel = new Label("SCORE: 0");
      scoreLabel.font = "16px Tahoma";
      scoreLabel.color = "white";
      scoreLabel.x = 10;
      scoreLabel.y = 5;
      this.rootScene.addChild(scoreLabel);
      score = 0;
      count = 0;
      enemy = [];
      total = 0;
      this.onload = function() {
        var beam, drawEnemy, fighter, hitCheck, moveBeam, moveFighter, startBeam;
        fighter = new Fighter();
        _this.rootScene.addChild(fighter);
        beam = new Sprite(4, 16);
        beam.flag = false;
        beam.x = fighter.x + 14;
        beam.y = fighter.y - 8;
        beam.image = _this.assets["image/beam.png"];
        beam._style.zIndex = 2;
        _this.rootScene.addChild(beam);
        _this.keybind(90, "a");
        drawEnemy = function() {
          var j, sp, _j, _k;
          for (i = _j = 0; _j <= 5; i = ++_j) {
            for (j = _k = 0; _k <= 1; j = ++_k) {
              sp = new Sprite(32, 32);
              sp.image = _this.assets["image/droid.png"];
              sp.x = j * (32 + 10);
              sp.y = i * 32 + 30;
              console.log(("" + count + ": sp.x:") + sp.j + ", y:" + sp.i);
              sp._style.zIndex = 2;
              _this.rootScene.addChild(sp);
              enemy.push(sp);
              count += 1;
            }
          }
          return total = count;
        };
        startBeam = function() {
          if (beam.flag === false) {
            if (_this.input.a) {
              beam.flag = true;
              beam.x = fighter.x + 14;
              return beam.y = fighter.y - 11;
            }
          }
        };
        moveBeam = function() {
          if (beam.flag) {
            beam.y -= 8;
            if (beam.y < -32) {
              return beam.flag = false;
            }
          }
        };
        moveFighter = function() {
          if (beam.flag === false) {
            beam.x = fighter.x + 14;
            return beam.y = fighter.y - 11;
          }
        };
        hitCheck = function() {
          var _j, _len1;
          for (_j = 0, _len1 = enemy.length; _j < _len1; _j++) {
            i = enemy[_j];
            if (beam.intersect(i)) {
              beam.flag = false;
              i.y = -9999;
              score += 1;
              total -= 1;
              if (total < 1) {
                setTimeout(drawEnemy(), 2000);
              }
            }
          }
          return scoreLabel.text = "SCORE: " + score;
        };
        drawEnemy();
        return _this.rootScene.addEventListener('enterframe', function() {
          startBeam();
          moveBeam();
          moveFighter();
          return hitCheck();
        });
      };
      this.start();
    }

    return Invader;

  })(Game);

  window.onload = function() {
    return new Invader;
  };

  Fighter = (function(_super) {

    __extends(Fighter, _super);

    function Fighter() {
      this.enterFrame = __bind(this.enterFrame, this);

      var game;
      Fighter.__super__.constructor.call(this, 32, 32);
      game = enchant.Game.instance;
      this.image = game.assets["image/apple.png"];
      this.x = game.width / 2;
      this.y = game.height - 40;
      this._style.zIndex = 1;
      this.addEventListener('enterframe', function() {
        if (game.input.left) {
          this.x -= 4;
          if (this.x < 0) {
            this.x = 0;
          }
        }
        if (game.input.right) {
          this.x += 4;
          if (this.x > (game.width - this.width)) {
            return this.x = game.width - this.width;
          }
        }
      });
    }

    Fighter.prototype.enterFrame = function() {
      var game;
      game = enchant.Game.instance;
      if (game.input.left) {
        this.x -= 4;
        if (this.x < 0) {
          this.x = 0;
        }
      }
      if (game.input.right) {
        this.x += 4;
        if (this.x > (game.width - this.width)) {
          return this.x = game.width - this.width;
        }
      }
    };

    return Fighter;

  })(Sprite);

  Beam = (function(_super) {

    __extends(Beam, _super);

    function Beam(fighter) {
      var _this = this;
      Beam.__super__.constructor.call(this, 4, 16);
      this.game = enchant.Game.instance;
      this.flag = false;
      this.image = this.game.assets["image/beam.png"];
      this.x = fighter.x + 14;
      this.y = fighter.y - 8;
      this._style.zIndex = 2;
      this.startBeam = function() {
        if (_this.flag === false) {
          if (_this.game.input.a) {
            _this.flag = true;
            _this.x = fighter.x + 14;
            return _this.y = fighter.y - 11;
          }
        }
      };
      this.moveBeam = function() {
        if (_this.flag) {
          _this.y -= 8;
          if (_this.y < -32) {
            return _this.flag = false;
          }
        }
      };
      this.addEventListener('enterframe', function() {
        _this.startBeam();
        return _this.moveBeam();
      });
    }

    return Beam;

  })(Sprite);

}).call(this);
